// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkpvmnrmsjsubhdupzec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrcHZtbnJtc2pzdWJoZHVwemVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzMzE5MDUsImV4cCI6MjA4MzkwNzkwNX0.R4MtqlMpCK3QqeUfqcuTTWd-F0DHDBnXoO-HKv061mM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});